[package]
name = "smmdb-client"
version = "0.1.0"
authors = ["Mario Reder <mreder1289@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
dirs = "3.0"
downcast-rs = "1"
env_logger = "0.7"
iced = { git = "https://github.com/hecrj/iced.git", commit = "4030326", features = [ "image", "tokio" ] }
iced_native = { git = "https://github.com/hecrj/iced.git", commit = "4030326" }
iced_wgpu = { git = "https://github.com/hecrj/iced.git", commit = "4030326" }
nfd = "0.0"
reqwest = "0.10"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_qs = "0.6"
smmdb-lib = { version = "1", features = [ "save" ], package = "smmdb", path = "../smmdb-lib" }

[profile]
[profile.dev]
opt-level = 1
