[package]
name = "smmdb"
version = "0.1.0"
authors = ["Mario Reder <mreder1289@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
dirs = "3.0"
env_logger = "0.7"
futures = "0.3"
iced = { git = "https://github.com/hecrj/iced.git", commit = "bbc6e91", features = [ "image", "tokio", "svg" ] }
iced_native = { git = "https://github.com/hecrj/iced.git", commit = "bbc6e91" }
iced_wgpu = { git = "https://github.com/hecrj/iced.git", commit = "bbc6e91" }
image = "0.23"
indexmap = "1.5"
lazy_static = "1"
nfd = { git = "https://github.com/saurvs/nfd-rs.git" }
reqwest = "0.10"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_qs = "0.6"
smmdb-lib = { version = "1", features = [ "save" ], package = "smmdb" }

[profile]
[profile.dev]
opt-level = 1
