[package]
name = "smmdb"
version = "0.1.2"
authors = ["Mario Reder <mreder1289@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
dirs = "3.0"
env_logger = "0.7"
futures = "0.3"
iced = { git = "https://github.com/Tarnadas/iced.git", commit = "ae6e007f0c50b7944bee6d367c3cf0123374f166", features = [ "image", "svg", "tokio" ] }
iced_native = { git = "https://github.com/Tarnadas/iced.git", commit = "ae6e007f0c50b7944bee6d367c3cf0123374f166" }
iced_wgpu = { git = "https://github.com/Tarnadas/iced.git", commit = "ae6e007f0c50b7944bee6d367c3cf0123374f166" }
image = "0.23"
indexmap = "1.6"
lazy_static = "1"
nfd = { version = "0.2", package = "nfd2" }
reqwest = "0.10"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_qs = "0.7"
smmdb-lib = { version = "1", features = [ "save" ], package = "smmdb" }

[profile]
[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
codegen-units = 1
