[package]
name = "smmdb"
version = "0.3.0"
authors = ["Mario Reder <mreder1289@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
dirs = "3"
env_logger = "0.8"
futures = "0.3"
human-panic = "1"
iced = { git = "https://github.com/hecrj/iced.git", commit = "d0402d072d3f4e128c55fc0a6184c5f7c712bb20", features = [ "image", "svg", "tokio" ] }
iced_native = { git = "https://github.com/hecrj/iced.git", commit = "d0402d072d3f4e128c55fc0a6184c5f7c712bb20" }
iced_wgpu = { git = "https://github.com/hecrj/iced.git", commit = "d0402d072d3f4e128c55fc0a6184c5f7c712bb20" }
image = "0.23"
indexmap = "1"
lazy_static = "1"
nfd = { version = "0.2", package = "nfd2" }
reqwest = "0.10"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
serde_qs = "0.7"
smmdb-lib = { version = "1", features = [ "save" ], package = "smmdb" }

[profile]
[profile.dev]
opt-level = 1

[profile.release]
lto = "fat"
codegen-units = 1
