[package]
name = "smmdb-client"
version = "0.1.0"
authors = ["Mario Reder <mreder1289@gmail.com>"]
edition = "2018"

[dependencies]
dirs = "3.0"
downcast-rs = "1"
env_logger = "0.7"
iced = { git = "https://github.com/hecrj/iced.git", commit = "4030326", features = [ "image" ] }
iced_native = { git = "https://github.com/hecrj/iced.git", commit = "4030326" }
iced_wgpu = { git = "https://github.com/hecrj/iced.git", commit = "4030326" }
nfd = "0.0"
smmdb = { version = "1", features = [ "save" ], path = "../smmdb-lib" }
