name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends libgtk-3-dev
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-23
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build Linux
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Build Windows
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu
      - name: Compress releases
        run: |
          export GZIP=-9 && \
          cd target/release && \
          tar czvf smmdb-client-linux.tar.gz smmdb && \
          cd ../../target/x86_64-pc-windows-gnu/release && \
          tar czvf smmdb-client-windows.tar.gz smmdb.exe
      - name: Update Draft Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: ${{ github.job }}
          name: Release ${{ github.job }}
          artifacts: "target/release/smmdb-client-linux.tar.gz,target/x86_64-pc-windows-gnu/release/smmdb-client-windows.tar.gz"
          draft: true
          allowUpdates: true

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-23
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Compress releases
        run: |
          export GZIP=-9 && \
          cd target/release && \
          tar czvf smmdb-client-macos.tar.gz smmdb
      - name: Update Draft Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.sha }}
          tag: ${{ github.job }}
          name: Release ${{ github.job }}
          artifacts: "target/release/smmdb-client-macos.tar.gz"
          draft: true
          allowUpdates: true
