name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends libgtk-3-dev binutils
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-08-23
          override: true
      - name: Install cross
        run: cargo install cross
      - name: Check
        run: cargo check
      - name: Build Linux
        run: cargo build --release
      - name: Build Windows
        run: cross build --release --target=x86_64-pc-windows-gnu
      - name: Compress releases
        run: |
          export GZIP=-9 && \
          cd target/release && \
          tar czvf smmdb-client-linux.tar.gz smmdb
          cd ../../target/x86_64-pc-windows-gnu/release && \
          tar czvf smmdb-client-windows.tar.gz smmdb.exe
      - name: Create Draft Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.sha }}
          name: Release ${{ github.job }}
          artifacts: "target/release/smmdb-client-linux.tar.gz,target/x86_64-pc-windows-gnu/release/smmdb-client-windows.tar.gz"
          draft: true
