name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y --no-install-recommends libgtk-3-dev
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-09
          override: true
          components: rustfmt, clippy
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-09
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  build-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-09-09
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
